default:
  SECRET_KEY: ''
  DEBUG: True
  LANGUAGE_CODE: 'en-us'
  TIME_ZONE: 'Europe/Moscow'
  USE_I18N: True
  USE_L10N: True
  USE_TZ: True
  INSTALLED_APPS:
    - django.contrib.admin
    - django.contrib.auth
    - django.contrib.contenttypes
    - django.contrib.sessions
    - django.contrib.messages
    - django.contrib.staticfiles
    - parts
    - rest_framework
    - corsheaders
  MIDDLEWARE:
    - django.middleware.security.SecurityMiddleware
    - django.contrib.sessions.middleware.SessionMiddleware
    - django.middleware.common.CommonMiddleware
    - django.middleware.csrf.CsrfViewMiddleware
    - django.contrib.auth.middleware.AuthenticationMiddleware
    - django.contrib.messages.middleware.MessageMiddleware
    - django.middleware.clickjacking.XFrameOptionsMiddleware
    - corsheaders.middleware.CorsMiddleware
    - django.middleware.common.CommonMiddleware

development:
  DEBUG: True
  ALLOWED_HOSTS:
    - '*'
  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: db.sqlite3

production:
  DEBUG: False
  ALLOWED_HOSTS:
    - '5.63.154.173'
  STATIC_ROOT: os.path.join(BASE_DIR, 'static/')
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql_psycopg2