default:
  SECRET_KEY: ''
  DEBUG: True
  LANGUAGE_CODE: 'en-us'
  TIME_ZONE: 'Europe/Moscow'
  USE_I18N: True
  USE_L10N: True
  USE_TZ: True
  REMOTE_CSV_FILE: parts.csv
  INSTALLED_APPS:
    - django.contrib.admin
    - django.contrib.auth
    - django.contrib.contenttypes
    - django.contrib.sessions
    - django.contrib.messages
    - django.contrib.staticfiles
    - parts
    - rest_framework
    - corsheaders
  MIDDLEWARE:
    - django.middleware.security.SecurityMiddleware
    - django.contrib.sessions.middleware.SessionMiddleware
    - django.middleware.common.CommonMiddleware
    - django.middleware.csrf.CsrfViewMiddleware
    - django.contrib.auth.middleware.AuthenticationMiddleware
    - django.contrib.messages.middleware.MessageMiddleware
    - django.middleware.clickjacking.XFrameOptionsMiddleware
    - corsheaders.middleware.CorsMiddleware
    - django.middleware.common.CommonMiddleware

development:
  DEBUG: True
  ALLOWED_HOSTS:
    - '*'
  CORS_ALLOW_ALL_ORIGINS: True
  CORS_ALLOWED_ORIGINS:
    - 'http://127.0.0.1:5500'

production:
  DEBUG: False
  REST_FRAMEWORK: 
    DEFAULT_RENDERER_CLASSES:
      'rest_framework.renderers.JSONRenderer'