# Generated by Django 3.1.3 on 2020-11-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=300)),
                ('unit', models.CharField(max_length=20)),
                ('count', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
