# Generated by Django 3.1.3 on 2021-02-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='count',
        ),
        migrations.RemoveField(
            model_name='part',
            name='image',
        ),
        migrations.RemoveField(
            model_name='part',
            name='unit',
        ),
    ]
